# -*- coding: utf-8 -*-
"""iea_jason_sql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KdgpCMbsgmRmHNMQ52-GI197p--F4LXj
"""

import json
import sqlite3
import os

if not os.path.exists('posts.json'):
  print("Please upload posts.jason file")
  from google.colab import files
  uploaded = files.upload()
else:
  print("posts.json cache found")

# create databse file
f = open('db.sqlite3',"w")
f.close()

# create connection object
conn = sqlite3.connect('db.sqlite3')
cur = conn.cursor()

print("Creating table Posts...Delete if it already exists...")

cur.executescript('''
DROP TABLE IF EXISTS Posts;

CREATE TABLE Posts (
        id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        publish_date TEXT,
        source TEXT,
        title TEXT,
        description LONGTEXT,
        tag TEXT
);
''')

# check if the posts.json file exists

print("Checking if posts.json file exists...")

fname = 'posts_saved_now.json'

if os.path.exists(fname) == False:
        print('posts.json file does not exist')
        quit()

import json
import sqlite3

# Define the file name and path to your JSON file
fname = 'posts.json'

# Establish a connection to the database
conn = sqlite3.connect('database_name.db')  # Replace 'database_name.db' with your actual database file
cur = conn.cursor()

# Create the table if it does not exist
cur.execute('''
CREATE TABLE IF NOT EXISTS Posts (
    publish_date TEXT,
    source TEXT,
    title TEXT,
    description TEXT,
    tag TEXT
)
''')

# Read the posts.json file and insert the data into the database
with open(fname, 'r') as file:
    json_data = json.load(file)

print("Inserting data into the database...")

# Prepare SQL statement
sql = '''INSERT OR IGNORE INTO Posts (publish_date, source, title, description, tag)
         VALUES (?, ?, ?, ?, ?)'''

for entry in json_data:
    publish_date = entry['publish_date']
    source = entry['source']
    title = entry['title']
    description = entry['description']
    tag = "IEA"
    cur.execute(sql, (publish_date, source, title, description, tag))

# Commit all changes at once
conn.commit()
print("Done!")

# Close the database connection
conn.close()

from google.colab import files
files.download('db.sqlite3')